### ISSUE TITLE
can't get dstc5_train_dev.tar.gz

### ISSUE THREAD

**Issue by zhangchizju2012** [seokhwankim/dstc5#3]
Hi,

I just follow your instruction and clone your repository.
But I didn't get dstc5_train_dev.tar.gz.
Can you tell me how to get this data?

Thanks.

**Comment by seokhwankim** [comment]
Hi,

The dataset was released under the limited license only for the DSTC5 participants.
Since the challenge period is already over, another license agreement is needed to get it at this moment.
If you need any further information, please contact to [the challenge organizers](http://workshop.colips.org/dstc5/contact.html).
Thanks.
